### ISSUE TITLE
SWProxy not showing "Found Summoners War API request"

### ISSUE THREAD

**Issue by HamzaLodhi** [kakaroto/SWProxy#198]
Usually it shows "Found Summoners War API Request" when i see other people use it on youtube. However when I use it the games loads normally but SWProxy does not show any information when the game loads. 

Here are the list of things that I have already tried:
1.  Turn off my antivirus's firewall (Mcafee)
2. Uninstalled my antivirus (Mcafee) along with other files related to Mcafee. (Reinstalled it later)
3. Turn off Windows Firewall
4. Run as administrator
5. Changed port number from 8080 to other numbers like 8086 etc.
6. Tried Use Summoners war exporter and faced the exact same difficulty (SWE not showing that it recieved information)
7. Gave permission to SWproxy to pass through my firewall for both public and private connections in the windows options. 

I checked the folder where the files are supposed to transfer to, however they are empty. I have tried downloading some different versions for the last 3 days but there is no luck. I would really appreciate some help.

**Comment by devbby** [comment]
Someone please correct me if I'm wrong but it seems that com2us has switched to ssl/tls connection. Essentially disabling this tool. I've noticed that this has also happened last month for a couple of days, then they reverted  back to http.

**Comment by fnk93** [comment]
Yes, they switched the whole app communication to https. One could rewrite this proxy on top of mitmproxy, but nonetheless you need to install the certificate somehow. For iOS it seems this process is not so difficult, but for every device with Android 7+ you'd need to root your phone. But afterwards still possible to extract the data.

**Comment by fnk93** [comment]
I will try to upload a fork tomorrow which is capable of doing this stuff in python tomorrow.

**Comment by fnk93** [comment]
https://github.com/fnk93/SWProxy-plugins

Edit: Hopefully this works, if not tell me.

**Comment by kakaroto** [comment]
I've stopped maintaining this, but feel free to continue the discussion and fix it and post the links to your fixes/forks here.
Thanks for stepping up!

**Comment by Sevendesign1230** [comment]
Hello
I have used your program for three years.
I really like this program very much.
But it was updated yesterday and SWproxy doesn't work now
Can you please help us?
Update the latest program and let it work Please

This program is really very important to me.
Thank you very very very very much.

**Comment by EvilzGaming** [comment]
I done everything like on the tutorial video and that doesn't work.

**Comment by ayienyei** [comment]
the swproxy not populating any data. i need the json file. i tried all including the video. i tried both android and iphone. nothing is working. please help.

**Comment by devbby** [comment]
@fnk93  Although I haven't tested your plugin I would **strongly advise against** step 

> 5. Install certificate in that app.

I'm not sure how Root Certificate Manager app facilitates this option, but I assume it modifies the manifest file of the APK to trust "user" certs. SW uses many anti cheat solutions both from external sources as well as their own custom anti-cheat detection. Modifying the APK itself poses a huge **BAN** risk as its **extremely easy to detect**. 

Using a transparent proxy was perfect due to it being untraceable and noninvasive, things we should aim for while trying to come up with a solution.  

In my own research, I've tried a similar approach, root, generate root CA cert for proxy, install cert as a system certificate, configure proxy to generate certs on the fly from root CA. hide root.
This looked very promising, no SSL errors in chrome, every https site accepted my custom certs, basic ssl mitm. This basically allowed us to be _invisible_ and establish a system wide trust for my CA. And yet it still didn't work. Any cert I threw at it was rejected. My best guess (needs confirming) they are using certificate pinning (probably custom) to only allow their own certs regardless of system certs.

@fnk93 Did you test your plugin after yesterdays update ? Also, if you "add the certificate to the apk" is it getting accepted ?

**Comment by fnk93** [comment]
@bobfbaby 
No, it does not modify the APK. Therefore **no Ban risk** because of that.
You need root for that app, because it pushes the certificate into the system certificate storage and renames it properly.

They are doing certificate pinning, but only for the appguard part. That's why the run command is only parsing hosts with "qpyou.cn" in it.

Yes, it's still running. I did not add the certificate into SW! I installed it into the system storage for certificates. And yes, it is accepted (at least for qpyou.cn host requests/responses)

**Comment by Xzandro** [comment]
There already are solutions in other projects like [SWEX](https://github.com/Xzandro/sw-exporter). Best to read the information here: https://github.com/Xzandro/sw-exporter/issues/243

@kakaroto Sorry, that you have to deal with this constant issues. I definitely know the pain. Thank you for your work years ago, especially in finding out the key. This work is still mandatory for al lthese tools to work and flourish so I can't stress this enough. Thank you!

**Comment by kakaroto** [comment]
Thank you @Xzandro for that last comment! I've been getting personal emails and new issue notifications because of this and it's definitely annoying considering I'm not maintaining this software or even playing the game anymore and I have no intentions of continuing.
Thanks for getting this fixed for everyone else. I'll be closing this issue in that case and I'll cross my fingers that people will read this answer and check out SWEX first before opening a new issue (yeah, I know they won't...).
