### ISSUE TITLE
Figure out where logging code went & consider moving to a plugin

### ISSUE THREAD

**Issue by azrethos** [kakaroto/SWProxy#39]
@kakaroto do you remember at one point there was logging code; i believe it logged cairos runs to a csv file; it certainly was a good candidate for a plugin, (AFAIK the code is not in master in any form now). I wanted to explore moving it to a plugin; perhaps disabled by default? 

Additionally how do you suggest we setup the concept of "disabled" plugins, (perhaps a folder? similar to `sites-available` `sites-enabled` for apache etc, [then they could be enabled via drag in drop by users])

**Comment by lstern** [comment]
@azrethos I created this logger and it was the main reason why I've implemented the plugin system. I've already moved/refactored the code to fit this plugin system. While I like this plugin and use it everyday, I agree with @kakaroto reason to reject  my push request 

> **Can you add feature X to the app ?**

> Whatever the feature is, I'm simply not interested. I've received numerous requests and proposals but this application has a single purpose, it is to export the runes to be used with the rune optimizer apps during free rune removal days. Any extra feature will make the app more and more feature-rich until it becomes something that is against the Terms of Service. I have to draw a line somewhere and I drew a line at "exporting runes and monster information", and I don't want to add anything more to the app.

**Comment by stanleykylee** [comment]
Should we create a separate repo for plugins? I would like this too.

**Comment by kakaroto** [comment]
Yeah, that feature was from @lstern, and I don't know where it is now (did you push the new plugin somewhere else ?). I do think a new repo for it would be good, and since @lstern is the one who implemented the plugin system, I think it would fit nicely into github.com/lstern/SWProxy-plugins, what do you think ?
As for enabled/disabled plugins. the plugin system has a way to activate/deactivate plugins (which we don't use), so I was thinking in the future that we could have a 'plugin selector' window in the GUI and users can enable/disable plugins through the interface and it would just call the activate/deactivate() APIs of the yapsy plugins. For now though, I think "delete file" or "move it away" is a good way of disabling plugins. No need to make it more complicated.
And btw, yapsy plugins can be made into directories, it might be easier to delete/remove plugins if they are one directory instead of being 2 files (.yapsy-plugin + .py). so maybe we should (eventually) move the plugins into directory-style plugins to make it easier for users to install/copy plugins.

**Comment by lstern** [comment]
https://github.com/lstern/SWProxy-plugins

**Comment by lstern** [comment]
the plugin system could be hacked to [supress the .yapsy-plugin file](https://sourceforge.net/p/yapsy/feature-requests/5/)

**Comment by dotneB** [comment]
I don't mind the yaspy-plugin file for metadata. Keeping it would make it easier for to display plugins info in the GUI for activate/deactivate.

Instead of supressing it I would rather we rename it to something like .swproxy-plugin via setPluginInfoExtension but that's very minor

I'm also for moving them to their own folders

We should implement ConfigurablePluginManager for actvate/desactivate but also for phasing out [swproxy.config](https://github.com/lstern/SWProxy-plugins/blob/master/swproxy.config)

I started working on a plugin to keep a log of all the SummonUnit and provide with stats. I had started by having it as a git subtree in my plugin folder, with the code would be hosted [here](https://github.com/dotneB/SWProxy-SummonStats-plugin). Should I instead fork [SWProxy-plugins](https://github.com/lstern/SWProxy-plugins) so that we only have one central repo containing all plugins. That would require @lstern to manage pull request for new plugin addition or update though.

**Comment by lstern** [comment]
the swproy.config is on SWProxy-plugins only and that was just me being
lazy. IMO, each plugin should implement its own config routine if
necessary.


I have no problem managin pull requests for the plugins repo.There's no
real need for central plugin repo but It would allow us to have more
control on what kind of stuff people are building using swproxy and
minimize silly stuff like plugins that spy arena opponent mobs (somebody
proposed it a while ago) or creating bots.

**Comment by azrethos** [comment]
I'd vote we remove the yapsy plugin files; i find them to be redundant, and would prefer just a wrapper class to access them, although @lstern i don't think it's worth necessarily "hacking" a solution, seems they should have support for this officially in the next version

**Comment by kakaroto** [comment]
I agree with @dotneB about the yapsy-plugin file being useful for having meaning name/description of the plugins (although that could be hacked into a class __doc__ comment) and having the plugins as directories would make it cleaner/better. 
I also like the idea of renaming the extension, I hadn't thought of that! 
As for the swproxy.config, I think the config should be read by swproxy and passed along to the plugins, so it would be 1 file for all. With the future in mind, I'd see it as being a writable file that the GUI's (eventual) preferences dialog would write the config to. This would include the listening port for the proxy, the list of activated plugins, and the plugin's own config. A json dictionary with the plugin's class name as key for each plugins' config would make sense.
It is however a little complex for the needs of today, so maybe ignore that for now and just create an issue for eventually evolving the config system.
