### ISSUE TITLE
[Windows] Loose files and console+gui

### ISSUE THREAD

**Issue by J-Saas** [kakaroto/SWProxy#68]
First off, I'm not very good with Python, in fact besides SWProxy I have very little experience with Python.

When that's said, what's with all the loose files that py2exe generates? When trying to compile the repo locally I don't even get working exes using the command **_python setup.py py2exe_**

However, running **_pyinstaller_** on **_SWProxy.py_** writes a new SWProxy.spec file that produces all the loose dependencies, I'm not sure why it's doing that.  Is it supposed to be doing that?

Also, does most windows users need both the GUI and the console? I'm attaching my own .SPEC file that consolidates all dependencies into a single executable and disables the console. Maybe someone with some more knowledge can educate a simple peasant.

http://hastebin.com/laquhuyepi.vbs

**Comment by kakaroto** [comment]
Hello peasant! :)

I don't like the loose files either, they're not much of a problem though, but I've read that there are even more loose files now than before, not sure why. I think pyinstaller might be the way to go, but I haven't looked at any of that in a while and I'm not the one that made the builds. As for the console, it was not supposed to be there, so I agree, it needs to be removed.
Anyways, once I get some free time, I'll look into that and make new packages that are 'nice and user friendly'
I'll keep your spec file here until the time I need to look into this issue. thanks

**Comment by lstern** [comment]
If you disable the console and GUI fails to load, the process will still be
running without any visible window and you will need to kill it manually

**Comment by stanleykylee** [comment]
When using pyinstaller, use the provided .spec file instead of SWProxy.py. This lets pyinstaller know that the spec file has already been created and will create the executable with the provided settings in the spec file. Using the provided .spec file should not produce extra loose files.

I'll see if I can get a hold of a windows VM again and create a new executable with fewer loose files (plugins will still be loose).

```
pyinstaller SWProxy.spec
```

**Comment by lstern** [comment]
Lets wait until we fix the network issue. Also, do we really need a GUI ? I remember we decided to build a GUI so we could have a proper mac app but @stanleykylee  said that he used to package the console version for his mac friends.

**Comment by Jbag1489** [comment]
The only thing I see that having the gui really helps is easily changing
the port for some people.

**Comment by stanleykylee** [comment]
Yes, the console version works fine. Everyone that I've been working with that uses the console with no issues.

As per Jbag, if we can incorporate a switch for the port in the console version, I don't see any problems.

Correct me if I'm wrong, but at this point, the GUI isn't really doing anything other than the port change?

**Comment by Jbag1489** [comment]
I don't see a reason to keep the gui around. I know there's the way to
change port with flags, but that's confusing for some people. Which is
fine, I understand everyone isn't as into computers as I and other people
are.

**Comment by azrethos** [comment]
personally, I never use the GUI

**Comment by Jbag1489** [comment]
The only reason I started was it was in the package after the new
encryption

**Comment by J-Saas** [comment]
Yeah, I read that many don't use it and some people can't even get the GUI working so unless the current one is improved upon I don't see the need for it.

@stanleykylee Yeah, but if you by accident run SWProxy.py the .spec file is re-written and all dependencies are distributed loosely into the .\dist\SWProxy\ folder. I have both versions on hand if you want them, but building SWProxy.py through pyinstaller gives you the same file. :)

**Comment by kakaroto** [comment]
I see plenty of reasons to keep the GUI around. First of all, the "if gui fails, process stays open" is indeed bad and needs to be fixed, but differently, not by having the console open, but by simply exiting instead.
I think there should be a way from python to detect if the app is running in windowed mode or not.
As for people not using the GUI, I've seen it but it seems to me like it's because there is an issue with the packaging, there shouldn't be a problem running the GUI, it's all packaged together! If it can't find QT, then that's because the .exe is wrong or something...
As for uses for the GUI, the very first thing is : "any 'common user' will feel completely lost simply because it's a console app". Most people are used to seeing an app, and a console 'scares them', so give them a GUI and it will look like a nicer app, more user-friendly, etc.. even if it brings nothing more in terms of features...
However, the GUI does bring features, such as : open PCAP file (which isn't yet implemented), and seems like 100 times easier than telling people to drop the file onto the second .exe (2 exe files, that's already confusing some people). also, you can start/stop the server, you can more easily set the port to listen to, and eventually, you will be able to select which plugins to enable/disable through the GUI.
I do agree though that the current GUI is very minimalistic. I suck at designing UI, so that's the best I could come up with. It needs to evolve, to get better and with more features, that's all.. It doesn't need to be removed simply because you don't use it.
My 2 cents.

**Comment by J-Saas** [comment]
@kakaroto I personally like the GUI too. I have a few ideas about a GUI but that can be brought up later. I feel that a true GUI shouldn't have the console backdrop like we have now and the argument that the process stays open even if the GUI fails to load while console is disabled is bad indeed.

Regarding the loose files, does anyne have any idea about why SWParser.py is replacing the .spec file? The untouched one works fine and compiles all the loose files into the EXE and shaves off about 10megs from the current archive. Is there a way to prevent overwriting the .spec? (Since I found out the hard way after a bit of searching)

**Comment by stanleykylee** [comment]
There is no way of preventing it (pyinstaller) from overwriting the .spec file. This is the default behaviour of pyinstaller. To answer your question about the loose files, that is also the default behaviour of pyinstaller.

To sum it up, pyinstaller by default, if not given a previously created .spec file will create a new .spec file and run through the python files attempting to include everything it needs as a dependency. It by default will not package the files into one binary executable. This is why the provided .spec file is needed. All of this has been defined (single file and where to look for plugins etc).

The only thing I can think of is to provide additional documentation for those that want to build their own binaries. That is, to run `pyinstaller SWProxy.spec` instead of `pyinstaller SWProxy.py`. At the same time, if you're running pyinstaller, you should really be reading up on what it does before you create it yourself?

**Comment by J-Saas** [comment]
@stanleykylee Thank you. I should've consulted the documentation more thoroughly regarding that. It has cleared a lot of things up!
