### ISSUE TITLE
Open Proxy

### ISSUE THREAD

**Issue by cdmichaelb** [kakaroto/SWProxy#77]
https://www.quakenet.org/help/security/what-is-an-open-proxy-g-line-for

Aside from not being able to use quakenet, I believe this is a seriously vulnerability if I understand what quakenet is saying on the topic. 

Is there anyway you can restrict it from the internet and only allow on local network?

**Comment by azrethos** [comment]
@cdmichaelb if you are behind any form of router (you very likely are) then you are 100% safe

(unless you are exposing your proxy port publically [you'd have to open the port and forward the IP in your router settings, or use a DMZ])

TLDR; 
you are hosting this locally, behind a router, should be 100% safe

**Comment by kakaroto** [comment]
Considering that this is meant to be used for less than 5 minutes inside your internal network and then stopped, not kept running on an public network, then I don't see a problem with that. It isn't meant to be used as a proxy, but only uses the proxy method as a means to grab the game's login information. Therefore, there is no reason or motivation behind making this into a complicate proxy with authentication support, etc...
As for quakenet, all you need to do is make it run on a random port instead of 8080.
