### ISSUE TITLE
ImportError: No module named yapsy; python noob here... Sorry for the trouble~

### ISSUE THREAD

**Issue by remytanx** [kakaroto/SWProxy#92]
Hi, I have been facing a problem when using the Parser. Could someone enlighten me on the issue. Hopefully the screenshot will display. Mainly, it is on the issue of "ImportError: No module named yapsy".
![screenshot from 2016-05-16 13 55 53](https://cloud.githubusercontent.com/assets/19382809/15281486/5080abbc-1b6e-11e6-9f51-ed1048d3be00.png)

**Comment by dANIel1989l** [comment]
are you using the source code or one of the OS (Win or Mac) bundles?

**Comment by remytanx** [comment]
I am using the source code. Running on Ubuntu 14.04. Currently I think I have python2.7, 3, 3m, 3.4 and 3.4m?

![screenshot from 2016-05-17 17 49 35](https://cloud.githubusercontent.com/assets/19382809/15318225/c0878b26-1c57-11e6-9b3b-2fa50f34082f.png)

**Comment by dANIel1989l** [comment]
OK then you are missing one or more of the dependencies: pycrypto, dpkt and yapsy

**Comment by remytanx** [comment]
Hi, please don't close the thread. Still bugged by the problem. Sorry kakaroto~

![screenshot from 2016-05-17 23 51 19](https://cloud.githubusercontent.com/assets/19382809/15329178/5c8f8262-1c8a-11e6-90ac-50f7210fb29f.png)

**Comment by remytanx** [comment]
This is the current problem I am facing~

![screenshot from 2016-05-17 23 54 14](https://cloud.githubusercontent.com/assets/19382809/15329294/b9e4b72a-1c8a-11e6-9d64-3befbe5a337c.png)

**Comment by dANIel1989l** [comment]
I don't use much linux, and the machine I have only has one installation of python. Is it possible that there is some conflict in which version of python has the dependencies installed vs the one that is attempting to run the proxy?

This command works on my single installation, maybe it will help you
`python2.7 SWProxy.py`

**Comment by kakaroto** [comment]
@remytanx no problem, you can still comment and get the help with the issue closed, but I closed it because it's not actually an issue of the software (issues are meant for reporting bugs or for asking for new features), it's more of a 'tech support' question, and considering instructions are already on the README, there's nothing to be done from our side to get it 'fixed' other than talk you through it, which can still be done with the issue closed.

As for your issue, pip says yapsy is already installed but SWProxy can't find it, which is weird, did you try with pip install --upgrade as it suggests? maybe you have and old version.. 
Something else I'd look into is the fact that pip says it's installed in /usr/local/lib/python2.7, I thought that python only looks for modules in/usr/lib/python2.7, so maybe see if there's a way to get it installed there instead..
Also, yapsy is available in ubuntu 14.04 (http://packages.ubuntu.com/trusty/python-yapsy) so maybe just try to do 'sudo apt-get install python-yapsy') and see if that fixes it.

@dANIel1989l The version here wouldn't affect it, pip says yapsy is installed in /usr/local/lib/python2.7 so it's installed in 2.7, and 'python' will usually be for python 2.7, since python 3 changed a lot of the syntax of the language, they can't point python to python3 without all python programs just failing.

**Comment by remytanx** [comment]
Yoz kakaroto,

Thanks for the clarification. Currently, I am still unable to resolve the issue on the ImportError. So I guess I have to use the windows version. Thanks for the help too.

Thank you dANIel1989l for the fast and prompt reply. Cheers~ :)

**Comment by iuriscotton** [comment]
Im having the same issues. Yapsy is up to date.

**Comment by msteudel** [comment]
BTW sometimes this happens if you have multiple versions of Python installed. On my mac at least I was able to fix this by using Homebrew to install Python and then install the various requirements.

**Comment by SurionA** [comment]
I was able to make it works by changing the way to install the dependencies:
```bash
$ python -m pip install pycrypto dpkt yapsy
```
The dependencies are installed and linked to my current python version.
Hope it would help.
