### ISSUE TITLE
Proxy seem to not able to be connected after latest patch

### ISSUE THREAD

**Issue by nlyt** [kakaroto/SWProxy#96]
Seems like there is an issue with connecting on Android version since the last update.

**Comment by porksmash** [comment]
I am not experiencing any issues. Can you describe exactly what is
happening for you?

**Comment by echaize** [comment]
I get the following error : 
`Running Proxy server at 192.168.0.66 on port 8080
ERROR - Exception while receiving from connection client <socket._socketobject object at 0x02125068> with reason error(10053, 'An established connection was aborted by the software in your host machine')
Traceback (most recent call last):
  File "proxy.pyo", line 266, in recv
error: [Errno 10053] An established connection was aborted by the software in your host machine
ERROR - Exception while receiving from connection client <socket._socketobject object at 0x021256C0> with reason error(10053, 'An established connection was aborted by the software in your host machine')
Traceback (most recent call last):
  File "proxy.pyo", line 266, in recv
error: [Errno 10053] An established connection was aborted by the software in your host machine
ERROR - Exception while receiving from connection client <socket._socketobject object at 0x021252D0> with reason error(10053, 'An established connection was aborted by the software in your host machine')
Traceback (most recent call last):
  File "proxy.pyo", line 266, in recv
error: [Errno 10053] An established connection was aborted by the software in your host machine
ERROR - Exception while receiving from connection client <socket._socketobject object at 0x02125688> with reason error(10053, 'An established connection was aborted by the software in your host machine')
Traceback (most recent call last):
  File "proxy.pyo", line 266, in recv
error: [Errno 10053] An established connection was aborted by the software in your host machine
ERROR - Exception while receiving from connection client <socket._socketobject object at 0x021258B8> with reason error(10053, 'An established connection was aborted by the software in your host machine')
Traceback (most recent call last):
  File "proxy.pyo", line 266, in recv
error: [Errno 10053] An established connection was aborted by the software in your host machine
ERROR - Exception while receiving from connection client <socket._socketobject object at 0x02125068> with reason error(10053, 'An established connection was aborted by the software in your host machine')
Traceback (most recent call last):
  File "proxy.pyo", line 266, in recv
error: [Errno 10053] An established connection was aborted by the software in your host machine
ERROR - <ProxyConnectionFailed - summonerswar-gb.com2us.net:80 - error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')>
Traceback (most recent call last):
  File "proxy.pyo", line 465, in _process_rlist
  File "proxy.pyo", line 389, in _process_request
ProxyConnectionFailed: <ProxyConnectionFailed - summonerswar-gb.com2us.net:80 - error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')>
ERROR - Exception while receiving from connection client <socket._socketobject object at 0x021255E0> with reason error(10054, 'An existing connection was forcibly closed by the remote host')
Traceback (most recent call last):
  File "proxy.pyo", line 266, in recv
error: [Errno 10054] An existing connection was forcibly closed by the remote host`

I use a iPhone 6s if that can help, I go the problem on Windows 7 and 10.

**Comment by echaize** [comment]
it work for me on mac.

**Comment by kakaroto** [comment]
`An established connection was aborted by the software in your host machine`
That sounds like a "your firewall blocked us". That might be what's causing you problems. I'll close this issue because it's not a real bug, but we can continue discussing it until you figure it out .
